import type { Metadata } from "next";
import Link from "next/link";
import { CookieSettingsLink } from "@/components/consent/cookie-settings-link";
import { LegalPage, P, Term, Ul } from "@/components/legal/legal-page";

/* ── Privacy Policy ────────────────────────────────────────────────────────
   Written against what this site actually does, not boilerplate: fan
   accounts, a double-opt-in newsletter, opt-in web push, one consent cookie
   gating YouTube requests, no analytics and no advertising. Update this
   document whenever any of that changes. ─────────────────────────────────── */

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How CTR Unified collects, uses and protects personal data on the CTR–JK Tyre FMSCI Indian National Car Racing Championship website.",
};

const CONTACT_EMAIL = "admin@ctrsports.in";

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      effectiveDate="1 September 2026"
      intro={
        <>
          <P>
            This policy explains what personal data CTR Unified collects when you use the
            official website of the CTR–JK Tyre FMSCI Indian National Car Racing Championship,
            why we collect it, who we share it with, and the choices and rights you have. It is
            written to comply with the Digital Personal Data Protection Act, 2023 (India).
          </P>
          <P>
            The short version: we collect only what the site needs to work — an email address
            if you create a fan account or subscribe to the newsletter, and your fan-zone
            activity if you take part. We run no advertising, no analytics trackers and no
            data sales, and third parties (YouTube) are contacted only after you say yes.
          </P>
        </>
      }
      sections={[
        {
          id: "who-we-are",
          title: "Who we are",
          body: (
            <>
              <P>
                The data fiduciary (controller) for this website is <strong>CTR Unified</strong>,
                organiser of the CTR–JK Tyre FMSCI Indian National Car Racing Championship.
              </P>
              <Ul>
                <Term term="Postal address">
                  29, Tilak Street, T. Nagar, Chennai, Tamil Nadu 600017, India
                </Term>
                <Term term="Email">{CONTACT_EMAIL}</Term>
                <Term term="Phone">+91 95000 16999</Term>
              </Ul>
              <P>
                This policy covers the public championship website only. The administration
                console used by championship staff, teams and officials is a separate system
                with its own access rules.
              </P>
            </>
          ),
        },
        {
          id: "data-we-collect",
          title: "Data we collect",
          body: (
            <>
              <P>We collect data in four situations, all of them initiated by you:</P>
              <Ul>
                <Term term="Fan account">
                  when you register we store your email address, your chosen display name and a
                  cryptographic hash of your password. We never store the password itself.
                </Term>
                <Term term="Newsletter">
                  when you subscribe we store your email address together with a record of your
                  confirmation (double opt-in): the time you subscribed and the time you clicked
                  the confirmation link.
                </Term>
                <Term term="Fan-zone activity">
                  if you are signed in and take part, we store your poll votes, race
                  predictions, favourite drivers and teams, saved articles and race-weekend
                  attendance responses (RSVPs), each linked to your account.
                </Term>
                <Term term="Push notifications">
                  if you switch on notifications, your browser gives us a push subscription
                  (a delivery endpoint and keys generated by your browser). It contains no
                  personal details and works only until you revoke it.
                </Term>
              </Ul>
              <P>
                Like every website, our hosting infrastructure also processes technical request
                data (IP address, browser type, requested page) in short-lived server logs used
                for security and reliability. We do not use this data to profile you.
              </P>
            </>
          ),
        },
        {
          id: "cookies",
          title: "Cookies and local storage",
          body: (
            <>
              <P>This site sets exactly two first-party cookies, and no third-party cookies:</P>
              <Ul>
                <Term term="ctr_fan_session">
                  keeps you signed in to your fan account. Strictly necessary; set only when you
                  sign in and removed when you sign out.
                </Term>
                <Term term="ctr_cookie_consent">
                  remembers your choice about third-party media (section 4) for 12 months, so we
                  do not ask on every visit.
                </Term>
              </Ul>
              <P>
                We use no advertising cookies, no analytics cookies and no cross-site tracking
                of any kind. You can review or change your choice at any time via{" "}
                <CookieSettingsLink className="font-bold text-text-5 underline decoration-2 underline-offset-2" />{" "}
                (also linked in the footer of every page).
              </P>
            </>
          ),
        },
        {
          id: "third-party-media",
          title: "Third-party media (YouTube)",
          body: (
            <>
              <P>
                Some videos on this site are hosted on YouTube. Loading a YouTube player or
                thumbnail sends a request to Google's servers, which discloses your IP address
                and browser details to Google — so we do not load anything from Google until
                you consent.
              </P>
              <P>
                Until then, video cards show our own artwork and video pages show a consent
                notice instead of the player. If you do consent, embeds use YouTube's
                privacy-enhanced domain (youtube-nocookie.com). Google's handling of that data
                is governed by{" "}
                <a
                  href="https://policies.google.com/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="font-bold text-text-5 underline decoration-2 underline-offset-2"
                >
                  Google's privacy policy
                </a>
                . Our own fonts, images and media are served from our infrastructure — the site
                makes no other third-party requests from your browser.
              </P>
            </>
          ),
        },
        {
          id: "how-we-use-data",
          title: "How we use your data",
          body: (
            <>
              <Ul>
                <Term term="Running your account">
                  signing you in, showing your fan-zone activity back to you, and sending
                  strictly service emails such as email verification and password resets.
                </Term>
                <Term term="Sending the newsletter">
                  delivering championship news and race-weekend digests to confirmed
                  subscribers. Every email contains a one-click unsubscribe link.
                </Term>
                <Term term="Sending push notifications">
                  delivering the categories of alerts you opted into. You can turn them off in
                  the site's notification settings or in your browser at any time.
                </Term>
                <Term term="Keeping the service safe">
                  preventing abuse, investigating security incidents and complying with legal
                  obligations.
                </Term>
              </Ul>
              <P>
                We do not sell personal data, we do not share it for advertising, and we do not
                use it for automated decision-making or profiling.
              </P>
            </>
          ),
        },
        {
          id: "processors",
          title: "Service providers we rely on",
          body: (
            <>
              <P>
                The site runs on infrastructure operated by a small number of service providers
                (data processors) who process data only on our instructions:
              </P>
              <Ul>
                <Term term="Vercel Inc. (USA)">
                  hosts and serves the website, including short-lived request logs.
                </Term>
                <Term term="Neon Inc. (USA)">
                  operates the PostgreSQL database where accounts, subscriptions and fan-zone
                  activity are stored.
                </Term>
                <Term term="Amazon Web Services (USA)">
                  stores uploaded media files (photographs, logos, documents) in Amazon S3.
                </Term>
                <Term term="Brevo (Sendinblue SAS, France)">
                  delivers our transactional emails and newsletters.
                </Term>
              </Ul>
              <P>
                Because some of these providers operate outside India, your data may be stored
                or processed abroad. We choose providers with strong contractual and technical
                safeguards, and transfers take place as permitted under the Digital Personal
                Data Protection Act, 2023.
              </P>
            </>
          ),
        },
        {
          id: "retention",
          title: "How long we keep data",
          body: (
            <>
              <Ul>
                <Term term="Fan accounts">
                  kept while your account exists; deleted when you delete your account or ask us
                  to.
                </Term>
                <Term term="Newsletter">
                  kept while your subscription is active. When you unsubscribe we keep a minimal
                  suppression record (your address and the unsubscribe date) so we never email
                  you again by mistake.
                </Term>
                <Term term="Push subscriptions">
                  deleted when you disable notifications or when your browser invalidates the
                  subscription.
                </Term>
                <Term term="Server logs">
                  rotated automatically by our hosting provider on short retention windows.
                </Term>
              </Ul>
            </>
          ),
        },
        {
          id: "your-rights",
          title: "Your rights",
          body: (
            <>
              <P>
                Under the Digital Personal Data Protection Act, 2023, you have the right to
                access a summary of the personal data we hold about you, to have inaccurate
                data corrected, to have your data erased, to withdraw consent at any time, to
                nominate another person to exercise your rights on your behalf, and to an
                accessible grievance process.
              </P>
              <P>
                Many of these you can do yourself: unsubscribe links live in every newsletter,
                cookie choices in Cookie settings, notification toggles in your account, and
                account details in your{" "}
                <Link
                  href="/account"
                  className="font-bold text-text-5 underline decoration-2 underline-offset-2"
                >
                  account page
                </Link>
                . For anything else — including access and erasure requests — email{" "}
                <a
                  href={`mailto:${CONTACT_EMAIL}`}
                  className="font-bold text-text-5 underline decoration-2 underline-offset-2"
                >
                  {CONTACT_EMAIL}
                </a>{" "}
                and we will respond within a reasonable time, and in any case within the
                timelines the law prescribes. If you are not satisfied with our response, you
                may complain to the Data Protection Board of India.
              </P>
            </>
          ),
        },
        {
          id: "children",
          title: "Children",
          body: (
            <P>
              The championship website's content is suitable for all ages, but fan accounts and
              the newsletter are intended for users aged 13 and over. If you are under 18,
              please use these features only with the consent of a parent or guardian, as
              required by Indian law. If we learn that we hold data of a child collected
              without the required consent, we will delete it.
            </P>
          ),
        },
        {
          id: "security",
          title: "Security",
          body: (
            <P>
              All traffic to the site is encrypted with TLS. Passwords are stored only as
              salted cryptographic hashes. Access to production data is restricted to
              championship staff who need it, and our providers hold recognised security
              certifications. No system is perfectly secure — if a breach ever affects your
              personal data, we will notify you and the Data Protection Board of India as the
              law requires.
            </P>
          ),
        },
        {
          id: "changes",
          title: "Changes to this policy",
          body: (
            <P>
              If we change what we collect or how we use it, we will update this page and its
              effective date, and for significant changes we will tell subscribers and account
              holders by email before the change takes effect. Continued use of the site after
              a change means the updated policy applies.
            </P>
          ),
        },
        {
          id: "contact",
          title: "Contact and grievances",
          body: (
            <P>
              Questions, requests and grievances about personal data go to our grievance
              contact at{" "}
              <a
                href={`mailto:${CONTACT_EMAIL}`}
                className="font-bold text-text-5 underline decoration-2 underline-offset-2"
              >
                {CONTACT_EMAIL}
              </a>{" "}
              or by post to CTR Unified, 29, Tilak Street, T. Nagar, Chennai, Tamil Nadu
              600017, India. Please include enough detail for us to identify your account or
              subscription. See also our{" "}
              <Link
                href="/terms-of-use"
                className="font-bold text-text-5 underline decoration-2 underline-offset-2"
              >
                Terms of Use
              </Link>
              .
            </P>
          ),
        },
      ]}
    />
  );
}
